//! Emit TypeScript from [`TsSchemaIr`] using OXC AST + codegen.
//!
//! No template string assembly of declarations — nodes are built with
//! [`oxc_ast::AstBuilder`] and printed by [`oxc_codegen::Codegen`].

use oxc_allocator::Allocator;
use oxc_ast::{
    ast::{ImportOrExportKind, Statement, TSType, TSTypeOperatorOperator, VariableDeclarationKind},
    AstBuilder, NONE,
};
use oxc_codegen::{Codegen, CodegenOptions, IndentChar};
use oxc_span::{SourceType, SPAN};
use oxc_syntax::number::NumberBase;

use super::ir::{ScalarType, Table, TsSchemaIr};
use super::Error;

/// Generate `schema.generated.ts` source from IR.
pub fn emit_typescript(ir: &TsSchemaIr) -> Result<String, Error> {
    let allocator = Allocator::default();
    let ast = AstBuilder::new(&allocator);
    let mut body = ast.vec();

    body.push(stmt_export_const_number(
        &ast,
        "APP_SCHEMA_VERSION",
        ir.schema_version as f64,
    ));
    body.push(stmt_export_const_string(&ast, "APP_SCHEMA", &ir.vos_source));

    for table in &ir.tables {
        body.push(stmt_export_interface_row(&ast, table));
    }

    body.push(stmt_export_interface_app_db(&ast, ir));
    body.push(stmt_export_type_alias_table_name(&ast));

    let program = ast.program(SPAN, SourceType::ts(), "", ast.vec(), None, ast.vec(), body);

    let printed = Codegen::new()
        .with_options(CodegenOptions {
            minify: false,
            // Match Biome / EditorConfig (4 spaces); OXC default is tabs.
            indent_char: IndentChar::Space,
            indent_width: 4,
            ..CodegenOptions::default()
        })
        .build(&program);
    let banner = "// @generated by `yydb generate`, do not edit!\n";
    Ok(format!("{banner}{}", printed.code))
}

fn stmt_export_const_number<'a>(ast: &AstBuilder<'a>, name: &str, value: f64) -> Statement<'a> {
    let binding = ast.binding_pattern(
        ast.binding_pattern_kind_binding_identifier(SPAN, ast.atom(name)),
        NONE,
        false,
    );
    let init = ast.expression_numeric_literal(SPAN, value, None, NumberBase::Decimal);
    let decl = ast.variable_declarator(
        SPAN,
        VariableDeclarationKind::Const,
        binding,
        Some(init),
        false,
    );
    export_decl(
        ast,
        ast.declaration_variable(SPAN, VariableDeclarationKind::Const, ast.vec1(decl), false),
    )
}

fn stmt_export_const_string<'a>(ast: &AstBuilder<'a>, name: &str, value: &str) -> Statement<'a> {
    let binding = ast.binding_pattern(
        ast.binding_pattern_kind_binding_identifier(SPAN, ast.atom(name)),
        NONE,
        false,
    );
    let init = ast.expression_string_literal(SPAN, ast.atom(value), None);
    let decl = ast.variable_declarator(
        SPAN,
        VariableDeclarationKind::Const,
        binding,
        Some(init),
        false,
    );
    export_decl(
        ast,
        ast.declaration_variable(SPAN, VariableDeclarationKind::Const, ast.vec1(decl), false),
    )
}

fn stmt_export_interface_row<'a>(ast: &AstBuilder<'a>, table: &Table) -> Statement<'a> {
    let iface_name = format!("{}Row", table.name);
    let mut members = ast.vec();
    for field in &table.fields {
        let key = ast.property_key_static_identifier(SPAN, ast.atom(field.name.as_str()));
        let ty = ts_type_from_scalar(ast, field.ty);
        let ann = ast.alloc_ts_type_annotation(SPAN, ty);
        members.push(ast.ts_signature_property_signature(
            SPAN,
            false,
            false,
            false,
            key,
            Some(ann),
        ));
    }
    let id = ast.binding_identifier(SPAN, ast.atom(iface_name.as_str()));
    let body = ast.alloc_ts_interface_body(SPAN, members);
    export_decl(
        ast,
        ast.declaration_ts_interface(SPAN, id, NONE, ast.vec(), body, false),
    )
}

fn stmt_export_interface_app_db<'a>(ast: &AstBuilder<'a>, ir: &TsSchemaIr) -> Statement<'a> {
    let mut table_members = ast.vec();
    for table in &ir.tables {
        let key = ast.property_key_static_identifier(SPAN, ast.atom(table.name.as_str()));
        let row_name = format!("{}Row", table.name);
        let ty = ast.ts_type_type_reference(
            SPAN,
            ast.ts_type_name_identifier_reference(SPAN, ast.atom(row_name.as_str())),
            NONE,
        );
        let ann = ast.alloc_ts_type_annotation(SPAN, ty);
        table_members.push(ast.ts_signature_property_signature(
            SPAN,
            false,
            false,
            false,
            key,
            Some(ann),
        ));
    }

    let tables_ty = ast.ts_type_type_literal(SPAN, table_members);
    let tables_key = ast.property_key_static_identifier(SPAN, "tables");
    let tables_ann = ast.alloc_ts_type_annotation(SPAN, tables_ty);
    let tables_sig = ast.ts_signature_property_signature(
        SPAN,
        false,
        false,
        false,
        tables_key,
        Some(tables_ann),
    );
    let mut app_members = ast.vec();
    app_members.push(tables_sig);

    let id = ast.binding_identifier(SPAN, "AppDb");
    let body = ast.alloc_ts_interface_body(SPAN, app_members);
    export_decl(
        ast,
        ast.declaration_ts_interface(SPAN, id, NONE, ast.vec(), body, false),
    )
}

fn stmt_export_type_alias_table_name<'a>(ast: &AstBuilder<'a>) -> Statement<'a> {
    // export type AppDbTableName = keyof AppDb["tables"];
    let app_db = ast.ts_type_type_reference(
        SPAN,
        ast.ts_type_name_identifier_reference(SPAN, "AppDb"),
        NONE,
    );
    let index = ast.ts_type_literal_type(SPAN, ast.ts_literal_string_literal(SPAN, "tables", None));
    let indexed = ast.ts_type_indexed_access_type(SPAN, app_db, index);
    let keyof_ty = ast.ts_type_type_operator_type(SPAN, TSTypeOperatorOperator::Keyof, indexed);
    let id = ast.binding_identifier(SPAN, "AppDbTableName");
    export_decl(
        ast,
        ast.declaration_ts_type_alias(SPAN, id, NONE, keyof_ty, false),
    )
}

fn ts_type_from_scalar<'a>(ast: &AstBuilder<'a>, ty: ScalarType) -> TSType<'a> {
    match ty {
        ScalarType::Uuid | ScalarType::Utf8 => ast.ts_type_string_keyword(SPAN),
        ScalarType::Bool => ast.ts_type_boolean_keyword(SPAN),
        ScalarType::I64 | ScalarType::F64 => ast.ts_type_number_keyword(SPAN),
    }
}

fn export_decl<'a>(
    ast: &AstBuilder<'a>,
    declaration: oxc_ast::ast::Declaration<'a>,
) -> Statement<'a> {
    Statement::from(ast.module_declaration_export_named_declaration(
        SPAN,
        Some(declaration),
        ast.vec(),
        None,
        ImportOrExportKind::Value,
        NONE,
    ))
}
