// @generated by `yydb generate`, do not edit!
export const APP_SCHEMA_VERSION = 1;
export const APP_SCHEMA = "table Setting {\n    @@id: uuid,\n    key: utf8,\n    value: utf8,\n}\n";
export interface SettingRow {
    id: string;
    key: string;
    value: string;
}
export interface AppDb {
    tables: {
        Setting: SettingRow;
    };
}
export type AppDbTableName = keyof AppDb["tables"];
